syntax = "proto3";

package holder.bill;

import "tel.proto";

message BillEvent {
    bytes eventId = 1;
    bytes billinId = 2;
    double amount = 3;
    int64 timestamp_s = 4;
};

message AppendRequest {
    repeated BillEvent events = 1;
};

message AppendResult {
    tel.OperationResult result = 1;
    GetResponse value = 2;
};

message GetRequest {
    bytes billingId = 1;
    int64 timestamp_s = 2;
};

message GetResponse {
    double amount = 1;
};

message FlushRequest {
    int64 timestamp_s = 1;
};

message FlushResponse {
    tel.OperationResult result = 1;
};

service Bill {
    rpc Append(AppendRequest) returns (AppendResult);
    rpc Get(GetRequest) returns (GetResponse);
    rpc Flush(FlushRequest) returns (FlushResponse);
};