syntax = "proto3";

package holder.bill;

import "tel.proto";

message BillEvent {
    bytes eventId = 1;
    bytes billerId = 2;
    int64 timestamp_s = 3;
    string billingKey = 4;
    double amount = 5;
};

message AppendRequest {
    repeated BillEvent events = 1;
};

message AppendResult {
    tel.OperationResult result = 1;
};

message GetRequest {
    int64 startTimestamp_s = 1;
    int64 endTimestamp_s = 2;
    uint32 limit = 3;
};

message GetResponse {
    repeated BillEvent events = 1;
};

message FlushRequest {
    int64 startTimestamp_s = 1;
    int64 endTimestamp_s = 2;
};

message FlushResponse {
    tel.OperationResult result = 1;
    int64 count = 2;
};

service Bill {
    rpc Append(AppendRequest) returns (AppendResult);
    rpc Get(GetRequest) returns (GetResponse);
    rpc Flush(FlushRequest) returns (FlushResponse);
};