syntax = "proto3";

package holder.limit;

import "tel.proto";

message LimitEvent {
    bytes eventId = 1;
    string limitId = 2;
    double amount = 3;
    int64 timestamp_s = 4;
};

message AppendRequest {
    repeated LimitEvent events = 1;
};

message AppendResult {
    tel.OperationResult result = 1;
    GetResponse value = 2;
};

message GetRequest {
    repeated string limitIds = 1;
};

message GetResponse {
    repeated double limitValues = 1;
};

message ResetRequest {
    repeated string limitIds = 1;
    int64 timestamp_s = 2;
};

message ResetResult {
    tel.OperationResult result = 1;
};

service Limit {
    rpc Append(AppendRequest) returns (AppendResult);
    rpc Get(GetRequest) returns (GetResponse);
    rpc Reset(ResetRequest) returns (ResetResult);
};
