syntax = "proto3";

package holder.obj;

import "resource.proto";
import "tel.proto";

enum HashType {
  SHA256 = 0;
  SHA512 = 1;
  SHA3_256 = 2;
  SHA3_512 = 3;
};

service Obj {
  rpc Write(WriteRequest) returns (Result);
  rpc Read(ReadRequest) returns (ContentResult);
  rpc Hash(HashRequest) returns (ContentResult);
  rpc Delete(DeleteRequest) returns (Result);
};

message WriteRequest {
  bytes id = 1;
  repeated string paths = 2; // required when creating file
  int64 offset = 3;          // -1 = end of file
  bytes data = 4;
};

message ReadRequest {
  bytes id = 1;
  int64 offset = 2; // -1 = end of file
  int64 data_len = 3;
};

message HashRequest {
  bytes id = 1;
  HashType hash_type = 2;
  int64 offset = 3;   // -1 = end of file
  int64 data_len = 4; // default = to file end
};

message DeleteRequest {
  bytes id = 1;
};

message Result { tel.OperationResult result = 1; };

message ContentResult {
  tel.OperationResult result = 1;
  bytes content = 2;
};
