syntax = "proto3";

package limit;

enum LimitResult {
  OK = 0;
  FAILED = 1;
  NOT_ENOUGH = 2;
  ID_NOT_FOUND = 3;
  RESOURCE_NOT_FOUND = 4;
};

service Limit {
  rpc Reserve(LimitReserve) returns (LimitReserveResponse);
  rpc Commit(LimitCommit) returns (LimitCommitResponse);
};

message LimitReserve {
  map<string, double> keyPrefixes = 1;
}

message LimitReserveResponse {
  LimitResult result = 1;
}

message LimitCommit {
  map<string, double> keyPrefixes = 1;
}

message LimitCommitResponse { LimitResult result = 1; };
