syntax = "proto3";

package minion;


message RouteHash {
  // order: [minionIds, subrouteIds]
  // hashN = len(minionIds) + len(subrouteIds)
  repeated bytes minionIds = 1;
  repeated bytes subrouteIds = 2;
  repeated uint32 hashRanges = 3;
  repeated uint32 hashSeeds = 4;
  repeated string properties = 5;
  float distanceScore = 6; // if not present - exact hash match
};

message RouteScore {
  // order: [minionIds, subrouteIds]
  // scorseN = len(minionIds) + len(subrouteIds)
  repeated bytes minionIds = 1;
  repeated bytes subrouteIds = 2;
  repeated float scores = 3;
};
