#include "parse_query.h"

#include <iostream>

// ANTLR Runtime header
#include <antlr4-runtime.h>

// Your generated headers
#include <sqlLexer.h>
#include <sqlParser.h>
#include <sqlBaseVisitor.h> // The base visitor class ANTLR generated for you

using namespace antlr4;


// ------------------------------------------------------------------
// 1. Define your custom Visitor
// ------------------------------------------------------------------
// Inherit from the generated BaseVisitor. You only need to override
// the functions for the specific grammar rules you care about.
class SqlVisitor : public sqlBaseVisitor {
public:
    std::any visitSelectStatement(sqlParser::SelectStatementContext *ctx) override {
        std::cout << "[VISITOR] Found a SELECT statement!\n";

        // visitChildren tells ANTLR to keep walking down the tree
        // to find the columns and table names.
        return visitChildren(ctx);
    }

    std::any visitColumnList(sqlParser::ColumnListContext *ctx) override {
        // ctx->getText() grabs the exact string from the query that matched this rule
        std::cout << "  -> Columns requested: " << ctx->getText() << "\n";
        return visitChildren(ctx);
    }

    std::any visitTableName(sqlParser::TableNameContext *ctx) override {
        std::cout << "  -> Target table: " << ctx->getText() << "\n";
        return visitChildren(ctx);
    }
};

// ------------------------------------------------------------------
// 2. The Parsing Function
// ------------------------------------------------------------------
void parseAndPrintSQL(const std::string& sqlString) {
    std::cout << "--- Parsing Query: " << sqlString << " ---\n";

    // A. Setup the input stream
    ANTLRInputStream input(sqlString);

    // B. Lexer reads characters and creates tokens
    sqlLexer lexer(&input);
    CommonTokenStream tokens(&lexer);

    // C. Parser reads tokens and builds the AST
    sqlParser parser(&tokens);

    // D. Start parsing at the 'query' rule (the top level of our grammar)
    tree::ParseTree *tree = parser.query();

    // (Optional) Print the raw LISP-style syntax tree generated by ANTLR
    // This is incredibly useful for debugging your grammar!
    std::cout << "Raw AST: " << tree->toStringTree(&parser) << "\n\n";

    // E. Traverse the tree using our custom Visitor
    SqlVisitor visitor;
    visitor.visit(tree);

    std::cout << "--------------------------------------\n\n";
}
